# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 2.8

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list

# Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/jiritu/caffe

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/jiritu/caffe

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running interactive CMake command-line interface..."
	/usr/bin/cmake -i .
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target install
install: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Install the project..."
	/usr/bin/cmake -P cmake_install.cmake
.PHONY : install

# Special rule for the target install
install/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Install the project..."
	/usr/bin/cmake -P cmake_install.cmake
.PHONY : install/fast

# Special rule for the target install/local
install/local: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing only the local directory..."
	/usr/bin/cmake -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local

# Special rule for the target install/local
install/local/fast: install/local
.PHONY : install/local/fast

# Special rule for the target list_install_components
list_install_components:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Available install components are: \"Unspecified\""
.PHONY : list_install_components

# Special rule for the target list_install_components
list_install_components/fast: list_install_components
.PHONY : list_install_components/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/jiritu/caffe/CMakeFiles /home/jiritu/caffe/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/jiritu/caffe/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named lint

# Build rule for target.
lint: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 lint
.PHONY : lint

# fast build rule for target.
lint/fast:
	$(MAKE) -f CMakeFiles/lint.dir/build.make CMakeFiles/lint.dir/build
.PHONY : lint/fast

#=============================================================================
# Target rules for targets named gtest

# Build rule for target.
gtest: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 gtest
.PHONY : gtest

# fast build rule for target.
gtest/fast:
	$(MAKE) -f src/gtest/CMakeFiles/gtest.dir/build.make src/gtest/CMakeFiles/gtest.dir/build
.PHONY : gtest/fast

#=============================================================================
# Target rules for targets named gtest_main

# Build rule for target.
gtest_main: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 gtest_main
.PHONY : gtest_main

# fast build rule for target.
gtest_main/fast:
	$(MAKE) -f src/gtest/CMakeFiles/gtest_main.dir/build.make src/gtest/CMakeFiles/gtest_main.dir/build
.PHONY : gtest_main/fast

#=============================================================================
# Target rules for targets named caffe

# Build rule for target.
caffe: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 caffe
.PHONY : caffe

# fast build rule for target.
caffe/fast:
	$(MAKE) -f src/caffe/CMakeFiles/caffe.dir/build.make src/caffe/CMakeFiles/caffe.dir/build
.PHONY : caffe/fast

#=============================================================================
# Target rules for targets named caffe_cu

# Build rule for target.
caffe_cu: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 caffe_cu
.PHONY : caffe_cu

# fast build rule for target.
caffe_cu/fast:
	$(MAKE) -f src/caffe/CMakeFiles/caffe_cu.dir/build.make src/caffe/CMakeFiles/caffe_cu.dir/build
.PHONY : caffe_cu/fast

#=============================================================================
# Target rules for targets named proto

# Build rule for target.
proto: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 proto
.PHONY : proto

# fast build rule for target.
proto/fast:
	$(MAKE) -f src/caffe/proto/CMakeFiles/proto.dir/build.make src/caffe/proto/CMakeFiles/proto.dir/build
.PHONY : proto/fast

#=============================================================================
# Target rules for targets named protoPy

# Build rule for target.
protoPy: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 protoPy
.PHONY : protoPy

# fast build rule for target.
protoPy/fast:
	$(MAKE) -f src/caffe/proto/CMakeFiles/protoPy.dir/build.make src/caffe/proto/CMakeFiles/protoPy.dir/build
.PHONY : protoPy/fast

#=============================================================================
# Target rules for targets named main_obj

# Build rule for target.
main_obj: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 main_obj
.PHONY : main_obj

# fast build rule for target.
main_obj/fast:
	$(MAKE) -f src/caffe/test/CMakeFiles/main_obj.dir/build.make src/caffe/test/CMakeFiles/main_obj.dir/build
.PHONY : main_obj/fast

#=============================================================================
# Target rules for targets named runtest

# Build rule for target.
runtest: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 runtest
.PHONY : runtest

# fast build rule for target.
runtest/fast:
	$(MAKE) -f src/caffe/test/CMakeFiles/runtest.dir/build.make src/caffe/test/CMakeFiles/runtest.dir/build
.PHONY : runtest/fast

#=============================================================================
# Target rules for targets named test.testbin

# Build rule for target.
test.testbin: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 test.testbin
.PHONY : test.testbin

# fast build rule for target.
test.testbin/fast:
	$(MAKE) -f src/caffe/test/CMakeFiles/test.testbin.dir/build.make src/caffe/test/CMakeFiles/test.testbin.dir/build
.PHONY : test.testbin/fast

#=============================================================================
# Target rules for targets named test_accuracy_layer.testbin

# Build rule for target.
test_accuracy_layer.testbin: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 test_accuracy_layer.testbin
.PHONY : test_accuracy_layer.testbin

# fast build rule for target.
test_accuracy_layer.testbin/fast:
	$(MAKE) -f src/caffe/test/CMakeFiles/test_accuracy_layer.testbin.dir/build.make src/caffe/test/CMakeFiles/test_accuracy_layer.testbin.dir/build
.PHONY : test_accuracy_layer.testbin/fast

#=============================================================================
# Target rules for targets named test_accuracy_layer.testbin.obj

# Build rule for target.
test_accuracy_layer.testbin.obj: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 test_accuracy_layer.testbin.obj
.PHONY : test_accuracy_layer.testbin.obj

# fast build rule for target.
test_accuracy_layer.testbin.obj/fast:
	$(MAKE) -f src/caffe/test/CMakeFiles/test_accuracy_layer.testbin.obj.dir/build.make src/caffe/test/CMakeFiles/test_accuracy_layer.testbin.obj.dir/build
.PHONY : test_accuracy_layer.testbin.obj/fast

#=============================================================================
# Target rules for targets named test_argmax_layer.testbin

# Build rule for target.
test_argmax_layer.testbin: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 test_argmax_layer.testbin
.PHONY : test_argmax_layer.testbin

# fast build rule for target.
test_argmax_layer.testbin/fast:
	$(MAKE) -f src/caffe/test/CMakeFiles/test_argmax_layer.testbin.dir/build.make src/caffe/test/CMakeFiles/test_argmax_layer.testbin.dir/build
.PHONY : test_argmax_layer.testbin/fast

#=============================================================================
# Target rules for targets named test_argmax_layer.testbin.obj

# Build rule for target.
test_argmax_layer.testbin.obj: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 test_argmax_layer.testbin.obj
.PHONY : test_argmax_layer.testbin.obj

# fast build rule for target.
test_argmax_layer.testbin.obj/fast:
	$(MAKE) -f src/caffe/test/CMakeFiles/test_argmax_layer.testbin.obj.dir/build.make src/caffe/test/CMakeFiles/test_argmax_layer.testbin.obj.dir/build
.PHONY : test_argmax_layer.testbin.obj/fast

#=============================================================================
# Target rules for targets named test_benchmark.testbin

# Build rule for target.
test_benchmark.testbin: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 test_benchmark.testbin
.PHONY : test_benchmark.testbin

# fast build rule for target.
test_benchmark.testbin/fast:
	$(MAKE) -f src/caffe/test/CMakeFiles/test_benchmark.testbin.dir/build.make src/caffe/test/CMakeFiles/test_benchmark.testbin.dir/build
.PHONY : test_benchmark.testbin/fast

#=============================================================================
# Target rules for targets named test_benchmark.testbin.obj

# Build rule for target.
test_benchmark.testbin.obj: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 test_benchmark.testbin.obj
.PHONY : test_benchmark.testbin.obj

# fast build rule for target.
test_benchmark.testbin.obj/fast:
	$(MAKE) -f src/caffe/test/CMakeFiles/test_benchmark.testbin.obj.dir/build.make src/caffe/test/CMakeFiles/test_benchmark.testbin.obj.dir/build
.PHONY : test_benchmark.testbin.obj/fast

#=============================================================================
# Target rules for targets named test_blob.testbin

# Build rule for target.
test_blob.testbin: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 test_blob.testbin
.PHONY : test_blob.testbin

# fast build rule for target.
test_blob.testbin/fast:
	$(MAKE) -f src/caffe/test/CMakeFiles/test_blob.testbin.dir/build.make src/caffe/test/CMakeFiles/test_blob.testbin.dir/build
.PHONY : test_blob.testbin/fast

#=============================================================================
# Target rules for targets named test_blob.testbin.obj

# Build rule for target.
test_blob.testbin.obj: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 test_blob.testbin.obj
.PHONY : test_blob.testbin.obj

# fast build rule for target.
test_blob.testbin.obj/fast:
	$(MAKE) -f src/caffe/test/CMakeFiles/test_blob.testbin.obj.dir/build.make src/caffe/test/CMakeFiles/test_blob.testbin.obj.dir/build
.PHONY : test_blob.testbin.obj/fast

#=============================================================================
# Target rules for targets named test_common.testbin

# Build rule for target.
test_common.testbin: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 test_common.testbin
.PHONY : test_common.testbin

# fast build rule for target.
test_common.testbin/fast:
	$(MAKE) -f src/caffe/test/CMakeFiles/test_common.testbin.dir/build.make src/caffe/test/CMakeFiles/test_common.testbin.dir/build
.PHONY : test_common.testbin/fast

#=============================================================================
# Target rules for targets named test_common.testbin.obj

# Build rule for target.
test_common.testbin.obj: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 test_common.testbin.obj
.PHONY : test_common.testbin.obj

# fast build rule for target.
test_common.testbin.obj/fast:
	$(MAKE) -f src/caffe/test/CMakeFiles/test_common.testbin.obj.dir/build.make src/caffe/test/CMakeFiles/test_common.testbin.obj.dir/build
.PHONY : test_common.testbin.obj/fast

#=============================================================================
# Target rules for targets named test_concat_layer.testbin

# Build rule for target.
test_concat_layer.testbin: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 test_concat_layer.testbin
.PHONY : test_concat_layer.testbin

# fast build rule for target.
test_concat_layer.testbin/fast:
	$(MAKE) -f src/caffe/test/CMakeFiles/test_concat_layer.testbin.dir/build.make src/caffe/test/CMakeFiles/test_concat_layer.testbin.dir/build
.PHONY : test_concat_layer.testbin/fast

#=============================================================================
# Target rules for targets named test_concat_layer.testbin.obj

# Build rule for target.
test_concat_layer.testbin.obj: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 test_concat_layer.testbin.obj
.PHONY : test_concat_layer.testbin.obj

# fast build rule for target.
test_concat_layer.testbin.obj/fast:
	$(MAKE) -f src/caffe/test/CMakeFiles/test_concat_layer.testbin.obj.dir/build.make src/caffe/test/CMakeFiles/test_concat_layer.testbin.obj.dir/build
.PHONY : test_concat_layer.testbin.obj/fast

#=============================================================================
# Target rules for targets named test_contrastive_loss_layer.testbin

# Build rule for target.
test_contrastive_loss_layer.testbin: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 test_contrastive_loss_layer.testbin
.PHONY : test_contrastive_loss_layer.testbin

# fast build rule for target.
test_contrastive_loss_layer.testbin/fast:
	$(MAKE) -f src/caffe/test/CMakeFiles/test_contrastive_loss_layer.testbin.dir/build.make src/caffe/test/CMakeFiles/test_contrastive_loss_layer.testbin.dir/build
.PHONY : test_contrastive_loss_layer.testbin/fast

#=============================================================================
# Target rules for targets named test_contrastive_loss_layer.testbin.obj

# Build rule for target.
test_contrastive_loss_layer.testbin.obj: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 test_contrastive_loss_layer.testbin.obj
.PHONY : test_contrastive_loss_layer.testbin.obj

# fast build rule for target.
test_contrastive_loss_layer.testbin.obj/fast:
	$(MAKE) -f src/caffe/test/CMakeFiles/test_contrastive_loss_layer.testbin.obj.dir/build.make src/caffe/test/CMakeFiles/test_contrastive_loss_layer.testbin.obj.dir/build
.PHONY : test_contrastive_loss_layer.testbin.obj/fast

#=============================================================================
# Target rules for targets named test_convolution_layer.testbin

# Build rule for target.
test_convolution_layer.testbin: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 test_convolution_layer.testbin
.PHONY : test_convolution_layer.testbin

# fast build rule for target.
test_convolution_layer.testbin/fast:
	$(MAKE) -f src/caffe/test/CMakeFiles/test_convolution_layer.testbin.dir/build.make src/caffe/test/CMakeFiles/test_convolution_layer.testbin.dir/build
.PHONY : test_convolution_layer.testbin/fast

#=============================================================================
# Target rules for targets named test_convolution_layer.testbin.obj

# Build rule for target.
test_convolution_layer.testbin.obj: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 test_convolution_layer.testbin.obj
.PHONY : test_convolution_layer.testbin.obj

# fast build rule for target.
test_convolution_layer.testbin.obj/fast:
	$(MAKE) -f src/caffe/test/CMakeFiles/test_convolution_layer.testbin.obj.dir/build.make src/caffe/test/CMakeFiles/test_convolution_layer.testbin.obj.dir/build
.PHONY : test_convolution_layer.testbin.obj/fast

#=============================================================================
# Target rules for targets named test_data_layer.testbin

# Build rule for target.
test_data_layer.testbin: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 test_data_layer.testbin
.PHONY : test_data_layer.testbin

# fast build rule for target.
test_data_layer.testbin/fast:
	$(MAKE) -f src/caffe/test/CMakeFiles/test_data_layer.testbin.dir/build.make src/caffe/test/CMakeFiles/test_data_layer.testbin.dir/build
.PHONY : test_data_layer.testbin/fast

#=============================================================================
# Target rules for targets named test_data_layer.testbin.obj

# Build rule for target.
test_data_layer.testbin.obj: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 test_data_layer.testbin.obj
.PHONY : test_data_layer.testbin.obj

# fast build rule for target.
test_data_layer.testbin.obj/fast:
	$(MAKE) -f src/caffe/test/CMakeFiles/test_data_layer.testbin.obj.dir/build.make src/caffe/test/CMakeFiles/test_data_layer.testbin.obj.dir/build
.PHONY : test_data_layer.testbin.obj/fast

#=============================================================================
# Target rules for targets named test_data_transformer.testbin

# Build rule for target.
test_data_transformer.testbin: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 test_data_transformer.testbin
.PHONY : test_data_transformer.testbin

# fast build rule for target.
test_data_transformer.testbin/fast:
	$(MAKE) -f src/caffe/test/CMakeFiles/test_data_transformer.testbin.dir/build.make src/caffe/test/CMakeFiles/test_data_transformer.testbin.dir/build
.PHONY : test_data_transformer.testbin/fast

#=============================================================================
# Target rules for targets named test_data_transformer.testbin.obj

# Build rule for target.
test_data_transformer.testbin.obj: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 test_data_transformer.testbin.obj
.PHONY : test_data_transformer.testbin.obj

# fast build rule for target.
test_data_transformer.testbin.obj/fast:
	$(MAKE) -f src/caffe/test/CMakeFiles/test_data_transformer.testbin.obj.dir/build.make src/caffe/test/CMakeFiles/test_data_transformer.testbin.obj.dir/build
.PHONY : test_data_transformer.testbin.obj/fast

#=============================================================================
# Target rules for targets named test_dummy_data_layer.testbin

# Build rule for target.
test_dummy_data_layer.testbin: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 test_dummy_data_layer.testbin
.PHONY : test_dummy_data_layer.testbin

# fast build rule for target.
test_dummy_data_layer.testbin/fast:
	$(MAKE) -f src/caffe/test/CMakeFiles/test_dummy_data_layer.testbin.dir/build.make src/caffe/test/CMakeFiles/test_dummy_data_layer.testbin.dir/build
.PHONY : test_dummy_data_layer.testbin/fast

#=============================================================================
# Target rules for targets named test_dummy_data_layer.testbin.obj

# Build rule for target.
test_dummy_data_layer.testbin.obj: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 test_dummy_data_layer.testbin.obj
.PHONY : test_dummy_data_layer.testbin.obj

# fast build rule for target.
test_dummy_data_layer.testbin.obj/fast:
	$(MAKE) -f src/caffe/test/CMakeFiles/test_dummy_data_layer.testbin.obj.dir/build.make src/caffe/test/CMakeFiles/test_dummy_data_layer.testbin.obj.dir/build
.PHONY : test_dummy_data_layer.testbin.obj/fast

#=============================================================================
# Target rules for targets named test_eltwise_layer.testbin

# Build rule for target.
test_eltwise_layer.testbin: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 test_eltwise_layer.testbin
.PHONY : test_eltwise_layer.testbin

# fast build rule for target.
test_eltwise_layer.testbin/fast:
	$(MAKE) -f src/caffe/test/CMakeFiles/test_eltwise_layer.testbin.dir/build.make src/caffe/test/CMakeFiles/test_eltwise_layer.testbin.dir/build
.PHONY : test_eltwise_layer.testbin/fast

#=============================================================================
# Target rules for targets named test_eltwise_layer.testbin.obj

# Build rule for target.
test_eltwise_layer.testbin.obj: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 test_eltwise_layer.testbin.obj
.PHONY : test_eltwise_layer.testbin.obj

# fast build rule for target.
test_eltwise_layer.testbin.obj/fast:
	$(MAKE) -f src/caffe/test/CMakeFiles/test_eltwise_layer.testbin.obj.dir/build.make src/caffe/test/CMakeFiles/test_eltwise_layer.testbin.obj.dir/build
.PHONY : test_eltwise_layer.testbin.obj/fast

#=============================================================================
# Target rules for targets named test_euclidean_loss_layer.testbin

# Build rule for target.
test_euclidean_loss_layer.testbin: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 test_euclidean_loss_layer.testbin
.PHONY : test_euclidean_loss_layer.testbin

# fast build rule for target.
test_euclidean_loss_layer.testbin/fast:
	$(MAKE) -f src/caffe/test/CMakeFiles/test_euclidean_loss_layer.testbin.dir/build.make src/caffe/test/CMakeFiles/test_euclidean_loss_layer.testbin.dir/build
.PHONY : test_euclidean_loss_layer.testbin/fast

#=============================================================================
# Target rules for targets named test_euclidean_loss_layer.testbin.obj

# Build rule for target.
test_euclidean_loss_layer.testbin.obj: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 test_euclidean_loss_layer.testbin.obj
.PHONY : test_euclidean_loss_layer.testbin.obj

# fast build rule for target.
test_euclidean_loss_layer.testbin.obj/fast:
	$(MAKE) -f src/caffe/test/CMakeFiles/test_euclidean_loss_layer.testbin.obj.dir/build.make src/caffe/test/CMakeFiles/test_euclidean_loss_layer.testbin.obj.dir/build
.PHONY : test_euclidean_loss_layer.testbin.obj/fast

#=============================================================================
# Target rules for targets named test_filler.testbin

# Build rule for target.
test_filler.testbin: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 test_filler.testbin
.PHONY : test_filler.testbin

# fast build rule for target.
test_filler.testbin/fast:
	$(MAKE) -f src/caffe/test/CMakeFiles/test_filler.testbin.dir/build.make src/caffe/test/CMakeFiles/test_filler.testbin.dir/build
.PHONY : test_filler.testbin/fast

#=============================================================================
# Target rules for targets named test_filler.testbin.obj

# Build rule for target.
test_filler.testbin.obj: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 test_filler.testbin.obj
.PHONY : test_filler.testbin.obj

# fast build rule for target.
test_filler.testbin.obj/fast:
	$(MAKE) -f src/caffe/test/CMakeFiles/test_filler.testbin.obj.dir/build.make src/caffe/test/CMakeFiles/test_filler.testbin.obj.dir/build
.PHONY : test_filler.testbin.obj/fast

#=============================================================================
# Target rules for targets named test_flatten_layer.testbin

# Build rule for target.
test_flatten_layer.testbin: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 test_flatten_layer.testbin
.PHONY : test_flatten_layer.testbin

# fast build rule for target.
test_flatten_layer.testbin/fast:
	$(MAKE) -f src/caffe/test/CMakeFiles/test_flatten_layer.testbin.dir/build.make src/caffe/test/CMakeFiles/test_flatten_layer.testbin.dir/build
.PHONY : test_flatten_layer.testbin/fast

#=============================================================================
# Target rules for targets named test_flatten_layer.testbin.obj

# Build rule for target.
test_flatten_layer.testbin.obj: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 test_flatten_layer.testbin.obj
.PHONY : test_flatten_layer.testbin.obj

# fast build rule for target.
test_flatten_layer.testbin.obj/fast:
	$(MAKE) -f src/caffe/test/CMakeFiles/test_flatten_layer.testbin.obj.dir/build.make src/caffe/test/CMakeFiles/test_flatten_layer.testbin.obj.dir/build
.PHONY : test_flatten_layer.testbin.obj/fast

#=============================================================================
# Target rules for targets named test_gradient_based_solver.testbin

# Build rule for target.
test_gradient_based_solver.testbin: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 test_gradient_based_solver.testbin
.PHONY : test_gradient_based_solver.testbin

# fast build rule for target.
test_gradient_based_solver.testbin/fast:
	$(MAKE) -f src/caffe/test/CMakeFiles/test_gradient_based_solver.testbin.dir/build.make src/caffe/test/CMakeFiles/test_gradient_based_solver.testbin.dir/build
.PHONY : test_gradient_based_solver.testbin/fast

#=============================================================================
# Target rules for targets named test_gradient_based_solver.testbin.obj

# Build rule for target.
test_gradient_based_solver.testbin.obj: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 test_gradient_based_solver.testbin.obj
.PHONY : test_gradient_based_solver.testbin.obj

# fast build rule for target.
test_gradient_based_solver.testbin.obj/fast:
	$(MAKE) -f src/caffe/test/CMakeFiles/test_gradient_based_solver.testbin.obj.dir/build.make src/caffe/test/CMakeFiles/test_gradient_based_solver.testbin.obj.dir/build
.PHONY : test_gradient_based_solver.testbin.obj/fast

#=============================================================================
# Target rules for targets named test_hdf5_output_layer.testbin

# Build rule for target.
test_hdf5_output_layer.testbin: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 test_hdf5_output_layer.testbin
.PHONY : test_hdf5_output_layer.testbin

# fast build rule for target.
test_hdf5_output_layer.testbin/fast:
	$(MAKE) -f src/caffe/test/CMakeFiles/test_hdf5_output_layer.testbin.dir/build.make src/caffe/test/CMakeFiles/test_hdf5_output_layer.testbin.dir/build
.PHONY : test_hdf5_output_layer.testbin/fast

#=============================================================================
# Target rules for targets named test_hdf5_output_layer.testbin.obj

# Build rule for target.
test_hdf5_output_layer.testbin.obj: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 test_hdf5_output_layer.testbin.obj
.PHONY : test_hdf5_output_layer.testbin.obj

# fast build rule for target.
test_hdf5_output_layer.testbin.obj/fast:
	$(MAKE) -f src/caffe/test/CMakeFiles/test_hdf5_output_layer.testbin.obj.dir/build.make src/caffe/test/CMakeFiles/test_hdf5_output_layer.testbin.obj.dir/build
.PHONY : test_hdf5_output_layer.testbin.obj/fast

#=============================================================================
# Target rules for targets named test_hdf5data_layer.testbin

# Build rule for target.
test_hdf5data_layer.testbin: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 test_hdf5data_layer.testbin
.PHONY : test_hdf5data_layer.testbin

# fast build rule for target.
test_hdf5data_layer.testbin/fast:
	$(MAKE) -f src/caffe/test/CMakeFiles/test_hdf5data_layer.testbin.dir/build.make src/caffe/test/CMakeFiles/test_hdf5data_layer.testbin.dir/build
.PHONY : test_hdf5data_layer.testbin/fast

#=============================================================================
# Target rules for targets named test_hdf5data_layer.testbin.obj

# Build rule for target.
test_hdf5data_layer.testbin.obj: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 test_hdf5data_layer.testbin.obj
.PHONY : test_hdf5data_layer.testbin.obj

# fast build rule for target.
test_hdf5data_layer.testbin.obj/fast:
	$(MAKE) -f src/caffe/test/CMakeFiles/test_hdf5data_layer.testbin.obj.dir/build.make src/caffe/test/CMakeFiles/test_hdf5data_layer.testbin.obj.dir/build
.PHONY : test_hdf5data_layer.testbin.obj/fast

#=============================================================================
# Target rules for targets named test_hinge_loss_layer.testbin

# Build rule for target.
test_hinge_loss_layer.testbin: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 test_hinge_loss_layer.testbin
.PHONY : test_hinge_loss_layer.testbin

# fast build rule for target.
test_hinge_loss_layer.testbin/fast:
	$(MAKE) -f src/caffe/test/CMakeFiles/test_hinge_loss_layer.testbin.dir/build.make src/caffe/test/CMakeFiles/test_hinge_loss_layer.testbin.dir/build
.PHONY : test_hinge_loss_layer.testbin/fast

#=============================================================================
# Target rules for targets named test_hinge_loss_layer.testbin.obj

# Build rule for target.
test_hinge_loss_layer.testbin.obj: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 test_hinge_loss_layer.testbin.obj
.PHONY : test_hinge_loss_layer.testbin.obj

# fast build rule for target.
test_hinge_loss_layer.testbin.obj/fast:
	$(MAKE) -f src/caffe/test/CMakeFiles/test_hinge_loss_layer.testbin.obj.dir/build.make src/caffe/test/CMakeFiles/test_hinge_loss_layer.testbin.obj.dir/build
.PHONY : test_hinge_loss_layer.testbin.obj/fast

#=============================================================================
# Target rules for targets named test_im2col_kernel.testbin

# Build rule for target.
test_im2col_kernel.testbin: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 test_im2col_kernel.testbin
.PHONY : test_im2col_kernel.testbin

# fast build rule for target.
test_im2col_kernel.testbin/fast:
	$(MAKE) -f src/caffe/test/CMakeFiles/test_im2col_kernel.testbin.dir/build.make src/caffe/test/CMakeFiles/test_im2col_kernel.testbin.dir/build
.PHONY : test_im2col_kernel.testbin/fast

#=============================================================================
# Target rules for targets named test_im2col_kernel.testbin.lib

# Build rule for target.
test_im2col_kernel.testbin.lib: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 test_im2col_kernel.testbin.lib
.PHONY : test_im2col_kernel.testbin.lib

# fast build rule for target.
test_im2col_kernel.testbin.lib/fast:
	$(MAKE) -f src/caffe/test/CMakeFiles/test_im2col_kernel.testbin.lib.dir/build.make src/caffe/test/CMakeFiles/test_im2col_kernel.testbin.lib.dir/build
.PHONY : test_im2col_kernel.testbin.lib/fast

#=============================================================================
# Target rules for targets named test_im2col_layer.testbin

# Build rule for target.
test_im2col_layer.testbin: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 test_im2col_layer.testbin
.PHONY : test_im2col_layer.testbin

# fast build rule for target.
test_im2col_layer.testbin/fast:
	$(MAKE) -f src/caffe/test/CMakeFiles/test_im2col_layer.testbin.dir/build.make src/caffe/test/CMakeFiles/test_im2col_layer.testbin.dir/build
.PHONY : test_im2col_layer.testbin/fast

#=============================================================================
# Target rules for targets named test_im2col_layer.testbin.obj

# Build rule for target.
test_im2col_layer.testbin.obj: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 test_im2col_layer.testbin.obj
.PHONY : test_im2col_layer.testbin.obj

# fast build rule for target.
test_im2col_layer.testbin.obj/fast:
	$(MAKE) -f src/caffe/test/CMakeFiles/test_im2col_layer.testbin.obj.dir/build.make src/caffe/test/CMakeFiles/test_im2col_layer.testbin.obj.dir/build
.PHONY : test_im2col_layer.testbin.obj/fast

#=============================================================================
# Target rules for targets named test_image_data_layer.testbin

# Build rule for target.
test_image_data_layer.testbin: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 test_image_data_layer.testbin
.PHONY : test_image_data_layer.testbin

# fast build rule for target.
test_image_data_layer.testbin/fast:
	$(MAKE) -f src/caffe/test/CMakeFiles/test_image_data_layer.testbin.dir/build.make src/caffe/test/CMakeFiles/test_image_data_layer.testbin.dir/build
.PHONY : test_image_data_layer.testbin/fast

#=============================================================================
# Target rules for targets named test_image_data_layer.testbin.obj

# Build rule for target.
test_image_data_layer.testbin.obj: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 test_image_data_layer.testbin.obj
.PHONY : test_image_data_layer.testbin.obj

# fast build rule for target.
test_image_data_layer.testbin.obj/fast:
	$(MAKE) -f src/caffe/test/CMakeFiles/test_image_data_layer.testbin.obj.dir/build.make src/caffe/test/CMakeFiles/test_image_data_layer.testbin.obj.dir/build
.PHONY : test_image_data_layer.testbin.obj/fast

#=============================================================================
# Target rules for targets named test_infogain_loss_layer.testbin

# Build rule for target.
test_infogain_loss_layer.testbin: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 test_infogain_loss_layer.testbin
.PHONY : test_infogain_loss_layer.testbin

# fast build rule for target.
test_infogain_loss_layer.testbin/fast:
	$(MAKE) -f src/caffe/test/CMakeFiles/test_infogain_loss_layer.testbin.dir/build.make src/caffe/test/CMakeFiles/test_infogain_loss_layer.testbin.dir/build
.PHONY : test_infogain_loss_layer.testbin/fast

#=============================================================================
# Target rules for targets named test_infogain_loss_layer.testbin.obj

# Build rule for target.
test_infogain_loss_layer.testbin.obj: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 test_infogain_loss_layer.testbin.obj
.PHONY : test_infogain_loss_layer.testbin.obj

# fast build rule for target.
test_infogain_loss_layer.testbin.obj/fast:
	$(MAKE) -f src/caffe/test/CMakeFiles/test_infogain_loss_layer.testbin.obj.dir/build.make src/caffe/test/CMakeFiles/test_infogain_loss_layer.testbin.obj.dir/build
.PHONY : test_infogain_loss_layer.testbin.obj/fast

#=============================================================================
# Target rules for targets named test_inner_product_layer.testbin

# Build rule for target.
test_inner_product_layer.testbin: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 test_inner_product_layer.testbin
.PHONY : test_inner_product_layer.testbin

# fast build rule for target.
test_inner_product_layer.testbin/fast:
	$(MAKE) -f src/caffe/test/CMakeFiles/test_inner_product_layer.testbin.dir/build.make src/caffe/test/CMakeFiles/test_inner_product_layer.testbin.dir/build
.PHONY : test_inner_product_layer.testbin/fast

#=============================================================================
# Target rules for targets named test_inner_product_layer.testbin.obj

# Build rule for target.
test_inner_product_layer.testbin.obj: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 test_inner_product_layer.testbin.obj
.PHONY : test_inner_product_layer.testbin.obj

# fast build rule for target.
test_inner_product_layer.testbin.obj/fast:
	$(MAKE) -f src/caffe/test/CMakeFiles/test_inner_product_layer.testbin.obj.dir/build.make src/caffe/test/CMakeFiles/test_inner_product_layer.testbin.obj.dir/build
.PHONY : test_inner_product_layer.testbin.obj/fast

#=============================================================================
# Target rules for targets named test_internal_thread.testbin

# Build rule for target.
test_internal_thread.testbin: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 test_internal_thread.testbin
.PHONY : test_internal_thread.testbin

# fast build rule for target.
test_internal_thread.testbin/fast:
	$(MAKE) -f src/caffe/test/CMakeFiles/test_internal_thread.testbin.dir/build.make src/caffe/test/CMakeFiles/test_internal_thread.testbin.dir/build
.PHONY : test_internal_thread.testbin/fast

#=============================================================================
# Target rules for targets named test_internal_thread.testbin.obj

# Build rule for target.
test_internal_thread.testbin.obj: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 test_internal_thread.testbin.obj
.PHONY : test_internal_thread.testbin.obj

# fast build rule for target.
test_internal_thread.testbin.obj/fast:
	$(MAKE) -f src/caffe/test/CMakeFiles/test_internal_thread.testbin.obj.dir/build.make src/caffe/test/CMakeFiles/test_internal_thread.testbin.obj.dir/build
.PHONY : test_internal_thread.testbin.obj/fast

#=============================================================================
# Target rules for targets named test_io.testbin

# Build rule for target.
test_io.testbin: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 test_io.testbin
.PHONY : test_io.testbin

# fast build rule for target.
test_io.testbin/fast:
	$(MAKE) -f src/caffe/test/CMakeFiles/test_io.testbin.dir/build.make src/caffe/test/CMakeFiles/test_io.testbin.dir/build
.PHONY : test_io.testbin/fast

#=============================================================================
# Target rules for targets named test_io.testbin.obj

# Build rule for target.
test_io.testbin.obj: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 test_io.testbin.obj
.PHONY : test_io.testbin.obj

# fast build rule for target.
test_io.testbin.obj/fast:
	$(MAKE) -f src/caffe/test/CMakeFiles/test_io.testbin.obj.dir/build.make src/caffe/test/CMakeFiles/test_io.testbin.obj.dir/build
.PHONY : test_io.testbin.obj/fast

#=============================================================================
# Target rules for targets named test_lrn_layer.testbin

# Build rule for target.
test_lrn_layer.testbin: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 test_lrn_layer.testbin
.PHONY : test_lrn_layer.testbin

# fast build rule for target.
test_lrn_layer.testbin/fast:
	$(MAKE) -f src/caffe/test/CMakeFiles/test_lrn_layer.testbin.dir/build.make src/caffe/test/CMakeFiles/test_lrn_layer.testbin.dir/build
.PHONY : test_lrn_layer.testbin/fast

#=============================================================================
# Target rules for targets named test_lrn_layer.testbin.obj

# Build rule for target.
test_lrn_layer.testbin.obj: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 test_lrn_layer.testbin.obj
.PHONY : test_lrn_layer.testbin.obj

# fast build rule for target.
test_lrn_layer.testbin.obj/fast:
	$(MAKE) -f src/caffe/test/CMakeFiles/test_lrn_layer.testbin.obj.dir/build.make src/caffe/test/CMakeFiles/test_lrn_layer.testbin.obj.dir/build
.PHONY : test_lrn_layer.testbin.obj/fast

#=============================================================================
# Target rules for targets named test_math_functions.testbin

# Build rule for target.
test_math_functions.testbin: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 test_math_functions.testbin
.PHONY : test_math_functions.testbin

# fast build rule for target.
test_math_functions.testbin/fast:
	$(MAKE) -f src/caffe/test/CMakeFiles/test_math_functions.testbin.dir/build.make src/caffe/test/CMakeFiles/test_math_functions.testbin.dir/build
.PHONY : test_math_functions.testbin/fast

#=============================================================================
# Target rules for targets named test_math_functions.testbin.obj

# Build rule for target.
test_math_functions.testbin.obj: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 test_math_functions.testbin.obj
.PHONY : test_math_functions.testbin.obj

# fast build rule for target.
test_math_functions.testbin.obj/fast:
	$(MAKE) -f src/caffe/test/CMakeFiles/test_math_functions.testbin.obj.dir/build.make src/caffe/test/CMakeFiles/test_math_functions.testbin.obj.dir/build
.PHONY : test_math_functions.testbin.obj/fast

#=============================================================================
# Target rules for targets named test_maxpool_dropout_layers.testbin

# Build rule for target.
test_maxpool_dropout_layers.testbin: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 test_maxpool_dropout_layers.testbin
.PHONY : test_maxpool_dropout_layers.testbin

# fast build rule for target.
test_maxpool_dropout_layers.testbin/fast:
	$(MAKE) -f src/caffe/test/CMakeFiles/test_maxpool_dropout_layers.testbin.dir/build.make src/caffe/test/CMakeFiles/test_maxpool_dropout_layers.testbin.dir/build
.PHONY : test_maxpool_dropout_layers.testbin/fast

#=============================================================================
# Target rules for targets named test_maxpool_dropout_layers.testbin.obj

# Build rule for target.
test_maxpool_dropout_layers.testbin.obj: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 test_maxpool_dropout_layers.testbin.obj
.PHONY : test_maxpool_dropout_layers.testbin.obj

# fast build rule for target.
test_maxpool_dropout_layers.testbin.obj/fast:
	$(MAKE) -f src/caffe/test/CMakeFiles/test_maxpool_dropout_layers.testbin.obj.dir/build.make src/caffe/test/CMakeFiles/test_maxpool_dropout_layers.testbin.obj.dir/build
.PHONY : test_maxpool_dropout_layers.testbin.obj/fast

#=============================================================================
# Target rules for targets named test_memory_data_layer.testbin

# Build rule for target.
test_memory_data_layer.testbin: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 test_memory_data_layer.testbin
.PHONY : test_memory_data_layer.testbin

# fast build rule for target.
test_memory_data_layer.testbin/fast:
	$(MAKE) -f src/caffe/test/CMakeFiles/test_memory_data_layer.testbin.dir/build.make src/caffe/test/CMakeFiles/test_memory_data_layer.testbin.dir/build
.PHONY : test_memory_data_layer.testbin/fast

#=============================================================================
# Target rules for targets named test_memory_data_layer.testbin.obj

# Build rule for target.
test_memory_data_layer.testbin.obj: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 test_memory_data_layer.testbin.obj
.PHONY : test_memory_data_layer.testbin.obj

# fast build rule for target.
test_memory_data_layer.testbin.obj/fast:
	$(MAKE) -f src/caffe/test/CMakeFiles/test_memory_data_layer.testbin.obj.dir/build.make src/caffe/test/CMakeFiles/test_memory_data_layer.testbin.obj.dir/build
.PHONY : test_memory_data_layer.testbin.obj/fast

#=============================================================================
# Target rules for targets named test_multinomial_logistic_loss_layer.testbin

# Build rule for target.
test_multinomial_logistic_loss_layer.testbin: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 test_multinomial_logistic_loss_layer.testbin
.PHONY : test_multinomial_logistic_loss_layer.testbin

# fast build rule for target.
test_multinomial_logistic_loss_layer.testbin/fast:
	$(MAKE) -f src/caffe/test/CMakeFiles/test_multinomial_logistic_loss_layer.testbin.dir/build.make src/caffe/test/CMakeFiles/test_multinomial_logistic_loss_layer.testbin.dir/build
.PHONY : test_multinomial_logistic_loss_layer.testbin/fast

#=============================================================================
# Target rules for targets named test_multinomial_logistic_loss_layer.testbin.obj

# Build rule for target.
test_multinomial_logistic_loss_layer.testbin.obj: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 test_multinomial_logistic_loss_layer.testbin.obj
.PHONY : test_multinomial_logistic_loss_layer.testbin.obj

# fast build rule for target.
test_multinomial_logistic_loss_layer.testbin.obj/fast:
	$(MAKE) -f src/caffe/test/CMakeFiles/test_multinomial_logistic_loss_layer.testbin.obj.dir/build.make src/caffe/test/CMakeFiles/test_multinomial_logistic_loss_layer.testbin.obj.dir/build
.PHONY : test_multinomial_logistic_loss_layer.testbin.obj/fast

#=============================================================================
# Target rules for targets named test_mvn_layer.testbin

# Build rule for target.
test_mvn_layer.testbin: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 test_mvn_layer.testbin
.PHONY : test_mvn_layer.testbin

# fast build rule for target.
test_mvn_layer.testbin/fast:
	$(MAKE) -f src/caffe/test/CMakeFiles/test_mvn_layer.testbin.dir/build.make src/caffe/test/CMakeFiles/test_mvn_layer.testbin.dir/build
.PHONY : test_mvn_layer.testbin/fast

#=============================================================================
# Target rules for targets named test_mvn_layer.testbin.obj

# Build rule for target.
test_mvn_layer.testbin.obj: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 test_mvn_layer.testbin.obj
.PHONY : test_mvn_layer.testbin.obj

# fast build rule for target.
test_mvn_layer.testbin.obj/fast:
	$(MAKE) -f src/caffe/test/CMakeFiles/test_mvn_layer.testbin.obj.dir/build.make src/caffe/test/CMakeFiles/test_mvn_layer.testbin.obj.dir/build
.PHONY : test_mvn_layer.testbin.obj/fast

#=============================================================================
# Target rules for targets named test_net.testbin

# Build rule for target.
test_net.testbin: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 test_net.testbin
.PHONY : test_net.testbin

# fast build rule for target.
test_net.testbin/fast:
	$(MAKE) -f src/caffe/test/CMakeFiles/test_net.testbin.dir/build.make src/caffe/test/CMakeFiles/test_net.testbin.dir/build
.PHONY : test_net.testbin/fast

#=============================================================================
# Target rules for targets named test_net.testbin.obj

# Build rule for target.
test_net.testbin.obj: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 test_net.testbin.obj
.PHONY : test_net.testbin.obj

# fast build rule for target.
test_net.testbin.obj/fast:
	$(MAKE) -f src/caffe/test/CMakeFiles/test_net.testbin.obj.dir/build.make src/caffe/test/CMakeFiles/test_net.testbin.obj.dir/build
.PHONY : test_net.testbin.obj/fast

#=============================================================================
# Target rules for targets named test_neuron_layer.testbin

# Build rule for target.
test_neuron_layer.testbin: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 test_neuron_layer.testbin
.PHONY : test_neuron_layer.testbin

# fast build rule for target.
test_neuron_layer.testbin/fast:
	$(MAKE) -f src/caffe/test/CMakeFiles/test_neuron_layer.testbin.dir/build.make src/caffe/test/CMakeFiles/test_neuron_layer.testbin.dir/build
.PHONY : test_neuron_layer.testbin/fast

#=============================================================================
# Target rules for targets named test_neuron_layer.testbin.obj

# Build rule for target.
test_neuron_layer.testbin.obj: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 test_neuron_layer.testbin.obj
.PHONY : test_neuron_layer.testbin.obj

# fast build rule for target.
test_neuron_layer.testbin.obj/fast:
	$(MAKE) -f src/caffe/test/CMakeFiles/test_neuron_layer.testbin.obj.dir/build.make src/caffe/test/CMakeFiles/test_neuron_layer.testbin.obj.dir/build
.PHONY : test_neuron_layer.testbin.obj/fast

#=============================================================================
# Target rules for targets named test_platform.testbin

# Build rule for target.
test_platform.testbin: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 test_platform.testbin
.PHONY : test_platform.testbin

# fast build rule for target.
test_platform.testbin/fast:
	$(MAKE) -f src/caffe/test/CMakeFiles/test_platform.testbin.dir/build.make src/caffe/test/CMakeFiles/test_platform.testbin.dir/build
.PHONY : test_platform.testbin/fast

#=============================================================================
# Target rules for targets named test_platform.testbin.obj

# Build rule for target.
test_platform.testbin.obj: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 test_platform.testbin.obj
.PHONY : test_platform.testbin.obj

# fast build rule for target.
test_platform.testbin.obj/fast:
	$(MAKE) -f src/caffe/test/CMakeFiles/test_platform.testbin.obj.dir/build.make src/caffe/test/CMakeFiles/test_platform.testbin.obj.dir/build
.PHONY : test_platform.testbin.obj/fast

#=============================================================================
# Target rules for targets named test_pooling_layer.testbin

# Build rule for target.
test_pooling_layer.testbin: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 test_pooling_layer.testbin
.PHONY : test_pooling_layer.testbin

# fast build rule for target.
test_pooling_layer.testbin/fast:
	$(MAKE) -f src/caffe/test/CMakeFiles/test_pooling_layer.testbin.dir/build.make src/caffe/test/CMakeFiles/test_pooling_layer.testbin.dir/build
.PHONY : test_pooling_layer.testbin/fast

#=============================================================================
# Target rules for targets named test_pooling_layer.testbin.obj

# Build rule for target.
test_pooling_layer.testbin.obj: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 test_pooling_layer.testbin.obj
.PHONY : test_pooling_layer.testbin.obj

# fast build rule for target.
test_pooling_layer.testbin.obj/fast:
	$(MAKE) -f src/caffe/test/CMakeFiles/test_pooling_layer.testbin.obj.dir/build.make src/caffe/test/CMakeFiles/test_pooling_layer.testbin.obj.dir/build
.PHONY : test_pooling_layer.testbin.obj/fast

#=============================================================================
# Target rules for targets named test_power_layer.testbin

# Build rule for target.
test_power_layer.testbin: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 test_power_layer.testbin
.PHONY : test_power_layer.testbin

# fast build rule for target.
test_power_layer.testbin/fast:
	$(MAKE) -f src/caffe/test/CMakeFiles/test_power_layer.testbin.dir/build.make src/caffe/test/CMakeFiles/test_power_layer.testbin.dir/build
.PHONY : test_power_layer.testbin/fast

#=============================================================================
# Target rules for targets named test_power_layer.testbin.obj

# Build rule for target.
test_power_layer.testbin.obj: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 test_power_layer.testbin.obj
.PHONY : test_power_layer.testbin.obj

# fast build rule for target.
test_power_layer.testbin.obj/fast:
	$(MAKE) -f src/caffe/test/CMakeFiles/test_power_layer.testbin.obj.dir/build.make src/caffe/test/CMakeFiles/test_power_layer.testbin.obj.dir/build
.PHONY : test_power_layer.testbin.obj/fast

#=============================================================================
# Target rules for targets named test_protobuf.testbin

# Build rule for target.
test_protobuf.testbin: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 test_protobuf.testbin
.PHONY : test_protobuf.testbin

# fast build rule for target.
test_protobuf.testbin/fast:
	$(MAKE) -f src/caffe/test/CMakeFiles/test_protobuf.testbin.dir/build.make src/caffe/test/CMakeFiles/test_protobuf.testbin.dir/build
.PHONY : test_protobuf.testbin/fast

#=============================================================================
# Target rules for targets named test_protobuf.testbin.obj

# Build rule for target.
test_protobuf.testbin.obj: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 test_protobuf.testbin.obj
.PHONY : test_protobuf.testbin.obj

# fast build rule for target.
test_protobuf.testbin.obj/fast:
	$(MAKE) -f src/caffe/test/CMakeFiles/test_protobuf.testbin.obj.dir/build.make src/caffe/test/CMakeFiles/test_protobuf.testbin.obj.dir/build
.PHONY : test_protobuf.testbin.obj/fast

#=============================================================================
# Target rules for targets named test_random_number_generator.testbin

# Build rule for target.
test_random_number_generator.testbin: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 test_random_number_generator.testbin
.PHONY : test_random_number_generator.testbin

# fast build rule for target.
test_random_number_generator.testbin/fast:
	$(MAKE) -f src/caffe/test/CMakeFiles/test_random_number_generator.testbin.dir/build.make src/caffe/test/CMakeFiles/test_random_number_generator.testbin.dir/build
.PHONY : test_random_number_generator.testbin/fast

#=============================================================================
# Target rules for targets named test_random_number_generator.testbin.obj

# Build rule for target.
test_random_number_generator.testbin.obj: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 test_random_number_generator.testbin.obj
.PHONY : test_random_number_generator.testbin.obj

# fast build rule for target.
test_random_number_generator.testbin.obj/fast:
	$(MAKE) -f src/caffe/test/CMakeFiles/test_random_number_generator.testbin.obj.dir/build.make src/caffe/test/CMakeFiles/test_random_number_generator.testbin.obj.dir/build
.PHONY : test_random_number_generator.testbin.obj/fast

#=============================================================================
# Target rules for targets named test_sigmoid_cross_entropy_loss_layer.testbin

# Build rule for target.
test_sigmoid_cross_entropy_loss_layer.testbin: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 test_sigmoid_cross_entropy_loss_layer.testbin
.PHONY : test_sigmoid_cross_entropy_loss_layer.testbin

# fast build rule for target.
test_sigmoid_cross_entropy_loss_layer.testbin/fast:
	$(MAKE) -f src/caffe/test/CMakeFiles/test_sigmoid_cross_entropy_loss_layer.testbin.dir/build.make src/caffe/test/CMakeFiles/test_sigmoid_cross_entropy_loss_layer.testbin.dir/build
.PHONY : test_sigmoid_cross_entropy_loss_layer.testbin/fast

#=============================================================================
# Target rules for targets named test_sigmoid_cross_entropy_loss_layer.testbin.obj

# Build rule for target.
test_sigmoid_cross_entropy_loss_layer.testbin.obj: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 test_sigmoid_cross_entropy_loss_layer.testbin.obj
.PHONY : test_sigmoid_cross_entropy_loss_layer.testbin.obj

# fast build rule for target.
test_sigmoid_cross_entropy_loss_layer.testbin.obj/fast:
	$(MAKE) -f src/caffe/test/CMakeFiles/test_sigmoid_cross_entropy_loss_layer.testbin.obj.dir/build.make src/caffe/test/CMakeFiles/test_sigmoid_cross_entropy_loss_layer.testbin.obj.dir/build
.PHONY : test_sigmoid_cross_entropy_loss_layer.testbin.obj/fast

#=============================================================================
# Target rules for targets named test_slice_layer.testbin

# Build rule for target.
test_slice_layer.testbin: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 test_slice_layer.testbin
.PHONY : test_slice_layer.testbin

# fast build rule for target.
test_slice_layer.testbin/fast:
	$(MAKE) -f src/caffe/test/CMakeFiles/test_slice_layer.testbin.dir/build.make src/caffe/test/CMakeFiles/test_slice_layer.testbin.dir/build
.PHONY : test_slice_layer.testbin/fast

#=============================================================================
# Target rules for targets named test_slice_layer.testbin.obj

# Build rule for target.
test_slice_layer.testbin.obj: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 test_slice_layer.testbin.obj
.PHONY : test_slice_layer.testbin.obj

# fast build rule for target.
test_slice_layer.testbin.obj/fast:
	$(MAKE) -f src/caffe/test/CMakeFiles/test_slice_layer.testbin.obj.dir/build.make src/caffe/test/CMakeFiles/test_slice_layer.testbin.obj.dir/build
.PHONY : test_slice_layer.testbin.obj/fast

#=============================================================================
# Target rules for targets named test_softmax_layer.testbin

# Build rule for target.
test_softmax_layer.testbin: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 test_softmax_layer.testbin
.PHONY : test_softmax_layer.testbin

# fast build rule for target.
test_softmax_layer.testbin/fast:
	$(MAKE) -f src/caffe/test/CMakeFiles/test_softmax_layer.testbin.dir/build.make src/caffe/test/CMakeFiles/test_softmax_layer.testbin.dir/build
.PHONY : test_softmax_layer.testbin/fast

#=============================================================================
# Target rules for targets named test_softmax_layer.testbin.obj

# Build rule for target.
test_softmax_layer.testbin.obj: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 test_softmax_layer.testbin.obj
.PHONY : test_softmax_layer.testbin.obj

# fast build rule for target.
test_softmax_layer.testbin.obj/fast:
	$(MAKE) -f src/caffe/test/CMakeFiles/test_softmax_layer.testbin.obj.dir/build.make src/caffe/test/CMakeFiles/test_softmax_layer.testbin.obj.dir/build
.PHONY : test_softmax_layer.testbin.obj/fast

#=============================================================================
# Target rules for targets named test_softmax_with_loss_layer.testbin

# Build rule for target.
test_softmax_with_loss_layer.testbin: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 test_softmax_with_loss_layer.testbin
.PHONY : test_softmax_with_loss_layer.testbin

# fast build rule for target.
test_softmax_with_loss_layer.testbin/fast:
	$(MAKE) -f src/caffe/test/CMakeFiles/test_softmax_with_loss_layer.testbin.dir/build.make src/caffe/test/CMakeFiles/test_softmax_with_loss_layer.testbin.dir/build
.PHONY : test_softmax_with_loss_layer.testbin/fast

#=============================================================================
# Target rules for targets named test_softmax_with_loss_layer.testbin.obj

# Build rule for target.
test_softmax_with_loss_layer.testbin.obj: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 test_softmax_with_loss_layer.testbin.obj
.PHONY : test_softmax_with_loss_layer.testbin.obj

# fast build rule for target.
test_softmax_with_loss_layer.testbin.obj/fast:
	$(MAKE) -f src/caffe/test/CMakeFiles/test_softmax_with_loss_layer.testbin.obj.dir/build.make src/caffe/test/CMakeFiles/test_softmax_with_loss_layer.testbin.obj.dir/build
.PHONY : test_softmax_with_loss_layer.testbin.obj/fast

#=============================================================================
# Target rules for targets named test_solver.testbin

# Build rule for target.
test_solver.testbin: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 test_solver.testbin
.PHONY : test_solver.testbin

# fast build rule for target.
test_solver.testbin/fast:
	$(MAKE) -f src/caffe/test/CMakeFiles/test_solver.testbin.dir/build.make src/caffe/test/CMakeFiles/test_solver.testbin.dir/build
.PHONY : test_solver.testbin/fast

#=============================================================================
# Target rules for targets named test_solver.testbin.obj

# Build rule for target.
test_solver.testbin.obj: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 test_solver.testbin.obj
.PHONY : test_solver.testbin.obj

# fast build rule for target.
test_solver.testbin.obj/fast:
	$(MAKE) -f src/caffe/test/CMakeFiles/test_solver.testbin.obj.dir/build.make src/caffe/test/CMakeFiles/test_solver.testbin.obj.dir/build
.PHONY : test_solver.testbin.obj/fast

#=============================================================================
# Target rules for targets named test_split_layer.testbin

# Build rule for target.
test_split_layer.testbin: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 test_split_layer.testbin
.PHONY : test_split_layer.testbin

# fast build rule for target.
test_split_layer.testbin/fast:
	$(MAKE) -f src/caffe/test/CMakeFiles/test_split_layer.testbin.dir/build.make src/caffe/test/CMakeFiles/test_split_layer.testbin.dir/build
.PHONY : test_split_layer.testbin/fast

#=============================================================================
# Target rules for targets named test_split_layer.testbin.obj

# Build rule for target.
test_split_layer.testbin.obj: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 test_split_layer.testbin.obj
.PHONY : test_split_layer.testbin.obj

# fast build rule for target.
test_split_layer.testbin.obj/fast:
	$(MAKE) -f src/caffe/test/CMakeFiles/test_split_layer.testbin.obj.dir/build.make src/caffe/test/CMakeFiles/test_split_layer.testbin.obj.dir/build
.PHONY : test_split_layer.testbin.obj/fast

#=============================================================================
# Target rules for targets named test_stochastic_pooling.testbin

# Build rule for target.
test_stochastic_pooling.testbin: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 test_stochastic_pooling.testbin
.PHONY : test_stochastic_pooling.testbin

# fast build rule for target.
test_stochastic_pooling.testbin/fast:
	$(MAKE) -f src/caffe/test/CMakeFiles/test_stochastic_pooling.testbin.dir/build.make src/caffe/test/CMakeFiles/test_stochastic_pooling.testbin.dir/build
.PHONY : test_stochastic_pooling.testbin/fast

#=============================================================================
# Target rules for targets named test_stochastic_pooling.testbin.obj

# Build rule for target.
test_stochastic_pooling.testbin.obj: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 test_stochastic_pooling.testbin.obj
.PHONY : test_stochastic_pooling.testbin.obj

# fast build rule for target.
test_stochastic_pooling.testbin.obj/fast:
	$(MAKE) -f src/caffe/test/CMakeFiles/test_stochastic_pooling.testbin.obj.dir/build.make src/caffe/test/CMakeFiles/test_stochastic_pooling.testbin.obj.dir/build
.PHONY : test_stochastic_pooling.testbin.obj/fast

#=============================================================================
# Target rules for targets named test_syncedmem.testbin

# Build rule for target.
test_syncedmem.testbin: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 test_syncedmem.testbin
.PHONY : test_syncedmem.testbin

# fast build rule for target.
test_syncedmem.testbin/fast:
	$(MAKE) -f src/caffe/test/CMakeFiles/test_syncedmem.testbin.dir/build.make src/caffe/test/CMakeFiles/test_syncedmem.testbin.dir/build
.PHONY : test_syncedmem.testbin/fast

#=============================================================================
# Target rules for targets named test_syncedmem.testbin.obj

# Build rule for target.
test_syncedmem.testbin.obj: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 test_syncedmem.testbin.obj
.PHONY : test_syncedmem.testbin.obj

# fast build rule for target.
test_syncedmem.testbin.obj/fast:
	$(MAKE) -f src/caffe/test/CMakeFiles/test_syncedmem.testbin.obj.dir/build.make src/caffe/test/CMakeFiles/test_syncedmem.testbin.obj.dir/build
.PHONY : test_syncedmem.testbin.obj/fast

#=============================================================================
# Target rules for targets named test_threshold_layer.testbin

# Build rule for target.
test_threshold_layer.testbin: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 test_threshold_layer.testbin
.PHONY : test_threshold_layer.testbin

# fast build rule for target.
test_threshold_layer.testbin/fast:
	$(MAKE) -f src/caffe/test/CMakeFiles/test_threshold_layer.testbin.dir/build.make src/caffe/test/CMakeFiles/test_threshold_layer.testbin.dir/build
.PHONY : test_threshold_layer.testbin/fast

#=============================================================================
# Target rules for targets named test_threshold_layer.testbin.obj

# Build rule for target.
test_threshold_layer.testbin.obj: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 test_threshold_layer.testbin.obj
.PHONY : test_threshold_layer.testbin.obj

# fast build rule for target.
test_threshold_layer.testbin.obj/fast:
	$(MAKE) -f src/caffe/test/CMakeFiles/test_threshold_layer.testbin.obj.dir/build.make src/caffe/test/CMakeFiles/test_threshold_layer.testbin.obj.dir/build
.PHONY : test_threshold_layer.testbin.obj/fast

#=============================================================================
# Target rules for targets named test_upgrade_proto.testbin

# Build rule for target.
test_upgrade_proto.testbin: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 test_upgrade_proto.testbin
.PHONY : test_upgrade_proto.testbin

# fast build rule for target.
test_upgrade_proto.testbin/fast:
	$(MAKE) -f src/caffe/test/CMakeFiles/test_upgrade_proto.testbin.dir/build.make src/caffe/test/CMakeFiles/test_upgrade_proto.testbin.dir/build
.PHONY : test_upgrade_proto.testbin/fast

#=============================================================================
# Target rules for targets named test_upgrade_proto.testbin.obj

# Build rule for target.
test_upgrade_proto.testbin.obj: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 test_upgrade_proto.testbin.obj
.PHONY : test_upgrade_proto.testbin.obj

# fast build rule for target.
test_upgrade_proto.testbin.obj/fast:
	$(MAKE) -f src/caffe/test/CMakeFiles/test_upgrade_proto.testbin.obj.dir/build.make src/caffe/test/CMakeFiles/test_upgrade_proto.testbin.obj.dir/build
.PHONY : test_upgrade_proto.testbin.obj/fast

#=============================================================================
# Target rules for targets named test_util_blas.testbin

# Build rule for target.
test_util_blas.testbin: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 test_util_blas.testbin
.PHONY : test_util_blas.testbin

# fast build rule for target.
test_util_blas.testbin/fast:
	$(MAKE) -f src/caffe/test/CMakeFiles/test_util_blas.testbin.dir/build.make src/caffe/test/CMakeFiles/test_util_blas.testbin.dir/build
.PHONY : test_util_blas.testbin/fast

#=============================================================================
# Target rules for targets named test_util_blas.testbin.obj

# Build rule for target.
test_util_blas.testbin.obj: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 test_util_blas.testbin.obj
.PHONY : test_util_blas.testbin.obj

# fast build rule for target.
test_util_blas.testbin.obj/fast:
	$(MAKE) -f src/caffe/test/CMakeFiles/test_util_blas.testbin.obj.dir/build.make src/caffe/test/CMakeFiles/test_util_blas.testbin.obj.dir/build
.PHONY : test_util_blas.testbin.obj/fast

#=============================================================================
# Target rules for targets named caffe.bin

# Build rule for target.
caffe.bin: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 caffe.bin
.PHONY : caffe.bin

# fast build rule for target.
caffe.bin/fast:
	$(MAKE) -f tools/CMakeFiles/caffe.bin.dir/build.make tools/CMakeFiles/caffe.bin.dir/build
.PHONY : caffe.bin/fast

# Manual pre-install relink rule for target.
caffe.bin/preinstall:
	$(MAKE) -f tools/CMakeFiles/caffe.bin.dir/build.make tools/CMakeFiles/caffe.bin.dir/preinstall
.PHONY : caffe.bin/preinstall

#=============================================================================
# Target rules for targets named compute_image_mean.bin

# Build rule for target.
compute_image_mean.bin: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 compute_image_mean.bin
.PHONY : compute_image_mean.bin

# fast build rule for target.
compute_image_mean.bin/fast:
	$(MAKE) -f tools/CMakeFiles/compute_image_mean.bin.dir/build.make tools/CMakeFiles/compute_image_mean.bin.dir/build
.PHONY : compute_image_mean.bin/fast

# Manual pre-install relink rule for target.
compute_image_mean.bin/preinstall:
	$(MAKE) -f tools/CMakeFiles/compute_image_mean.bin.dir/build.make tools/CMakeFiles/compute_image_mean.bin.dir/preinstall
.PHONY : compute_image_mean.bin/preinstall

#=============================================================================
# Target rules for targets named convert_imageset.bin

# Build rule for target.
convert_imageset.bin: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 convert_imageset.bin
.PHONY : convert_imageset.bin

# fast build rule for target.
convert_imageset.bin/fast:
	$(MAKE) -f tools/CMakeFiles/convert_imageset.bin.dir/build.make tools/CMakeFiles/convert_imageset.bin.dir/build
.PHONY : convert_imageset.bin/fast

# Manual pre-install relink rule for target.
convert_imageset.bin/preinstall:
	$(MAKE) -f tools/CMakeFiles/convert_imageset.bin.dir/build.make tools/CMakeFiles/convert_imageset.bin.dir/preinstall
.PHONY : convert_imageset.bin/preinstall

#=============================================================================
# Target rules for targets named device_query.bin

# Build rule for target.
device_query.bin: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 device_query.bin
.PHONY : device_query.bin

# fast build rule for target.
device_query.bin/fast:
	$(MAKE) -f tools/CMakeFiles/device_query.bin.dir/build.make tools/CMakeFiles/device_query.bin.dir/build
.PHONY : device_query.bin/fast

# Manual pre-install relink rule for target.
device_query.bin/preinstall:
	$(MAKE) -f tools/CMakeFiles/device_query.bin.dir/build.make tools/CMakeFiles/device_query.bin.dir/preinstall
.PHONY : device_query.bin/preinstall

#=============================================================================
# Target rules for targets named dump_network.bin

# Build rule for target.
dump_network.bin: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 dump_network.bin
.PHONY : dump_network.bin

# fast build rule for target.
dump_network.bin/fast:
	$(MAKE) -f tools/CMakeFiles/dump_network.bin.dir/build.make tools/CMakeFiles/dump_network.bin.dir/build
.PHONY : dump_network.bin/fast

# Manual pre-install relink rule for target.
dump_network.bin/preinstall:
	$(MAKE) -f tools/CMakeFiles/dump_network.bin.dir/build.make tools/CMakeFiles/dump_network.bin.dir/preinstall
.PHONY : dump_network.bin/preinstall

#=============================================================================
# Target rules for targets named extract_features.bin

# Build rule for target.
extract_features.bin: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 extract_features.bin
.PHONY : extract_features.bin

# fast build rule for target.
extract_features.bin/fast:
	$(MAKE) -f tools/CMakeFiles/extract_features.bin.dir/build.make tools/CMakeFiles/extract_features.bin.dir/build
.PHONY : extract_features.bin/fast

# Manual pre-install relink rule for target.
extract_features.bin/preinstall:
	$(MAKE) -f tools/CMakeFiles/extract_features.bin.dir/build.make tools/CMakeFiles/extract_features.bin.dir/preinstall
.PHONY : extract_features.bin/preinstall

#=============================================================================
# Target rules for targets named finetune_net.bin

# Build rule for target.
finetune_net.bin: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 finetune_net.bin
.PHONY : finetune_net.bin

# fast build rule for target.
finetune_net.bin/fast:
	$(MAKE) -f tools/CMakeFiles/finetune_net.bin.dir/build.make tools/CMakeFiles/finetune_net.bin.dir/build
.PHONY : finetune_net.bin/fast

# Manual pre-install relink rule for target.
finetune_net.bin/preinstall:
	$(MAKE) -f tools/CMakeFiles/finetune_net.bin.dir/build.make tools/CMakeFiles/finetune_net.bin.dir/preinstall
.PHONY : finetune_net.bin/preinstall

#=============================================================================
# Target rules for targets named net_speed_benchmark.bin

# Build rule for target.
net_speed_benchmark.bin: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 net_speed_benchmark.bin
.PHONY : net_speed_benchmark.bin

# fast build rule for target.
net_speed_benchmark.bin/fast:
	$(MAKE) -f tools/CMakeFiles/net_speed_benchmark.bin.dir/build.make tools/CMakeFiles/net_speed_benchmark.bin.dir/build
.PHONY : net_speed_benchmark.bin/fast

# Manual pre-install relink rule for target.
net_speed_benchmark.bin/preinstall:
	$(MAKE) -f tools/CMakeFiles/net_speed_benchmark.bin.dir/build.make tools/CMakeFiles/net_speed_benchmark.bin.dir/preinstall
.PHONY : net_speed_benchmark.bin/preinstall

#=============================================================================
# Target rules for targets named test_net.bin

# Build rule for target.
test_net.bin: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 test_net.bin
.PHONY : test_net.bin

# fast build rule for target.
test_net.bin/fast:
	$(MAKE) -f tools/CMakeFiles/test_net.bin.dir/build.make tools/CMakeFiles/test_net.bin.dir/build
.PHONY : test_net.bin/fast

# Manual pre-install relink rule for target.
test_net.bin/preinstall:
	$(MAKE) -f tools/CMakeFiles/test_net.bin.dir/build.make tools/CMakeFiles/test_net.bin.dir/preinstall
.PHONY : test_net.bin/preinstall

#=============================================================================
# Target rules for targets named train_net.bin

# Build rule for target.
train_net.bin: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 train_net.bin
.PHONY : train_net.bin

# fast build rule for target.
train_net.bin/fast:
	$(MAKE) -f tools/CMakeFiles/train_net.bin.dir/build.make tools/CMakeFiles/train_net.bin.dir/build
.PHONY : train_net.bin/fast

# Manual pre-install relink rule for target.
train_net.bin/preinstall:
	$(MAKE) -f tools/CMakeFiles/train_net.bin.dir/build.make tools/CMakeFiles/train_net.bin.dir/preinstall
.PHONY : train_net.bin/preinstall

#=============================================================================
# Target rules for targets named upgrade_net_proto_binary.bin

# Build rule for target.
upgrade_net_proto_binary.bin: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 upgrade_net_proto_binary.bin
.PHONY : upgrade_net_proto_binary.bin

# fast build rule for target.
upgrade_net_proto_binary.bin/fast:
	$(MAKE) -f tools/CMakeFiles/upgrade_net_proto_binary.bin.dir/build.make tools/CMakeFiles/upgrade_net_proto_binary.bin.dir/build
.PHONY : upgrade_net_proto_binary.bin/fast

# Manual pre-install relink rule for target.
upgrade_net_proto_binary.bin/preinstall:
	$(MAKE) -f tools/CMakeFiles/upgrade_net_proto_binary.bin.dir/build.make tools/CMakeFiles/upgrade_net_proto_binary.bin.dir/preinstall
.PHONY : upgrade_net_proto_binary.bin/preinstall

#=============================================================================
# Target rules for targets named upgrade_net_proto_text.bin

# Build rule for target.
upgrade_net_proto_text.bin: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 upgrade_net_proto_text.bin
.PHONY : upgrade_net_proto_text.bin

# fast build rule for target.
upgrade_net_proto_text.bin/fast:
	$(MAKE) -f tools/CMakeFiles/upgrade_net_proto_text.bin.dir/build.make tools/CMakeFiles/upgrade_net_proto_text.bin.dir/build
.PHONY : upgrade_net_proto_text.bin/fast

# Manual pre-install relink rule for target.
upgrade_net_proto_text.bin/preinstall:
	$(MAKE) -f tools/CMakeFiles/upgrade_net_proto_text.bin.dir/build.make tools/CMakeFiles/upgrade_net_proto_text.bin.dir/preinstall
.PHONY : upgrade_net_proto_text.bin/preinstall

#=============================================================================
# Target rules for targets named convert_cifar_data

# Build rule for target.
convert_cifar_data: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 convert_cifar_data
.PHONY : convert_cifar_data

# fast build rule for target.
convert_cifar_data/fast:
	$(MAKE) -f examples/CMakeFiles/convert_cifar_data.dir/build.make examples/CMakeFiles/convert_cifar_data.dir/build
.PHONY : convert_cifar_data/fast

#=============================================================================
# Target rules for targets named convert_mnist_data

# Build rule for target.
convert_mnist_data: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 convert_mnist_data
.PHONY : convert_mnist_data

# fast build rule for target.
convert_mnist_data/fast:
	$(MAKE) -f examples/CMakeFiles/convert_mnist_data.dir/build.make examples/CMakeFiles/convert_mnist_data.dir/build
.PHONY : convert_mnist_data/fast

#=============================================================================
# Target rules for targets named convert_mnist_siamese_data

# Build rule for target.
convert_mnist_siamese_data: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 convert_mnist_siamese_data
.PHONY : convert_mnist_siamese_data

# fast build rule for target.
convert_mnist_siamese_data/fast:
	$(MAKE) -f examples/CMakeFiles/convert_mnist_siamese_data.dir/build.make examples/CMakeFiles/convert_mnist_siamese_data.dir/build
.PHONY : convert_mnist_siamese_data/fast

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... install"
	@echo "... install/local"
	@echo "... lint"
	@echo "... list_install_components"
	@echo "... rebuild_cache"
	@echo "... gtest"
	@echo "... gtest_main"
	@echo "... caffe"
	@echo "... caffe_cu"
	@echo "... proto"
	@echo "... protoPy"
	@echo "... main_obj"
	@echo "... runtest"
	@echo "... test.testbin"
	@echo "... test_accuracy_layer.testbin"
	@echo "... test_accuracy_layer.testbin.obj"
	@echo "... test_argmax_layer.testbin"
	@echo "... test_argmax_layer.testbin.obj"
	@echo "... test_benchmark.testbin"
	@echo "... test_benchmark.testbin.obj"
	@echo "... test_blob.testbin"
	@echo "... test_blob.testbin.obj"
	@echo "... test_common.testbin"
	@echo "... test_common.testbin.obj"
	@echo "... test_concat_layer.testbin"
	@echo "... test_concat_layer.testbin.obj"
	@echo "... test_contrastive_loss_layer.testbin"
	@echo "... test_contrastive_loss_layer.testbin.obj"
	@echo "... test_convolution_layer.testbin"
	@echo "... test_convolution_layer.testbin.obj"
	@echo "... test_data_layer.testbin"
	@echo "... test_data_layer.testbin.obj"
	@echo "... test_data_transformer.testbin"
	@echo "... test_data_transformer.testbin.obj"
	@echo "... test_dummy_data_layer.testbin"
	@echo "... test_dummy_data_layer.testbin.obj"
	@echo "... test_eltwise_layer.testbin"
	@echo "... test_eltwise_layer.testbin.obj"
	@echo "... test_euclidean_loss_layer.testbin"
	@echo "... test_euclidean_loss_layer.testbin.obj"
	@echo "... test_filler.testbin"
	@echo "... test_filler.testbin.obj"
	@echo "... test_flatten_layer.testbin"
	@echo "... test_flatten_layer.testbin.obj"
	@echo "... test_gradient_based_solver.testbin"
	@echo "... test_gradient_based_solver.testbin.obj"
	@echo "... test_hdf5_output_layer.testbin"
	@echo "... test_hdf5_output_layer.testbin.obj"
	@echo "... test_hdf5data_layer.testbin"
	@echo "... test_hdf5data_layer.testbin.obj"
	@echo "... test_hinge_loss_layer.testbin"
	@echo "... test_hinge_loss_layer.testbin.obj"
	@echo "... test_im2col_kernel.testbin"
	@echo "... test_im2col_kernel.testbin.lib"
	@echo "... test_im2col_layer.testbin"
	@echo "... test_im2col_layer.testbin.obj"
	@echo "... test_image_data_layer.testbin"
	@echo "... test_image_data_layer.testbin.obj"
	@echo "... test_infogain_loss_layer.testbin"
	@echo "... test_infogain_loss_layer.testbin.obj"
	@echo "... test_inner_product_layer.testbin"
	@echo "... test_inner_product_layer.testbin.obj"
	@echo "... test_internal_thread.testbin"
	@echo "... test_internal_thread.testbin.obj"
	@echo "... test_io.testbin"
	@echo "... test_io.testbin.obj"
	@echo "... test_lrn_layer.testbin"
	@echo "... test_lrn_layer.testbin.obj"
	@echo "... test_math_functions.testbin"
	@echo "... test_math_functions.testbin.obj"
	@echo "... test_maxpool_dropout_layers.testbin"
	@echo "... test_maxpool_dropout_layers.testbin.obj"
	@echo "... test_memory_data_layer.testbin"
	@echo "... test_memory_data_layer.testbin.obj"
	@echo "... test_multinomial_logistic_loss_layer.testbin"
	@echo "... test_multinomial_logistic_loss_layer.testbin.obj"
	@echo "... test_mvn_layer.testbin"
	@echo "... test_mvn_layer.testbin.obj"
	@echo "... test_net.testbin"
	@echo "... test_net.testbin.obj"
	@echo "... test_neuron_layer.testbin"
	@echo "... test_neuron_layer.testbin.obj"
	@echo "... test_platform.testbin"
	@echo "... test_platform.testbin.obj"
	@echo "... test_pooling_layer.testbin"
	@echo "... test_pooling_layer.testbin.obj"
	@echo "... test_power_layer.testbin"
	@echo "... test_power_layer.testbin.obj"
	@echo "... test_protobuf.testbin"
	@echo "... test_protobuf.testbin.obj"
	@echo "... test_random_number_generator.testbin"
	@echo "... test_random_number_generator.testbin.obj"
	@echo "... test_sigmoid_cross_entropy_loss_layer.testbin"
	@echo "... test_sigmoid_cross_entropy_loss_layer.testbin.obj"
	@echo "... test_slice_layer.testbin"
	@echo "... test_slice_layer.testbin.obj"
	@echo "... test_softmax_layer.testbin"
	@echo "... test_softmax_layer.testbin.obj"
	@echo "... test_softmax_with_loss_layer.testbin"
	@echo "... test_softmax_with_loss_layer.testbin.obj"
	@echo "... test_solver.testbin"
	@echo "... test_solver.testbin.obj"
	@echo "... test_split_layer.testbin"
	@echo "... test_split_layer.testbin.obj"
	@echo "... test_stochastic_pooling.testbin"
	@echo "... test_stochastic_pooling.testbin.obj"
	@echo "... test_syncedmem.testbin"
	@echo "... test_syncedmem.testbin.obj"
	@echo "... test_threshold_layer.testbin"
	@echo "... test_threshold_layer.testbin.obj"
	@echo "... test_upgrade_proto.testbin"
	@echo "... test_upgrade_proto.testbin.obj"
	@echo "... test_util_blas.testbin"
	@echo "... test_util_blas.testbin.obj"
	@echo "... caffe.bin"
	@echo "... compute_image_mean.bin"
	@echo "... convert_imageset.bin"
	@echo "... device_query.bin"
	@echo "... dump_network.bin"
	@echo "... extract_features.bin"
	@echo "... finetune_net.bin"
	@echo "... net_speed_benchmark.bin"
	@echo "... test_net.bin"
	@echo "... train_net.bin"
	@echo "... upgrade_net_proto_binary.bin"
	@echo "... upgrade_net_proto_text.bin"
	@echo "... convert_cifar_data"
	@echo "... convert_mnist_data"
	@echo "... convert_mnist_siamese_data"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

